[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pjh-mcm-templates"
version = "0.0.1"
dependencies = [

]

[tool.setuptools.packages.find]
where = ["."]
include = ["templates*"]