[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcm-kit"
version = "0.0.2"
dependencies = [
    "numpy", "pandas", "pytest"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mcm_kit*"]